name: Reportar bugs
description: Reportar comportamentos inesperados no projeto.
title: "[Bug]: "
body:
  - type: textarea
    id: descricao
    attributes:
      label: Descrição
      description: Descreva o problema
      placeholder: "Por exemplo: o botão para criar conta não aparece..."
    validations:
      required: true

  - type: textarea
    id: onde
    attributes:
      label: Onde ocorre o problema
      description: Em que parte do projeto ocorre este problema?
      placeholder: "Por exemplo: este problema acontece na página principal, canto superior direito, botão chamado de Nova Conta..."
    validations:
      required: true

  - type: textarea
    id: passos
    attributes:
      label: Passos para reproduzir o problema
      description: Nos conte os passos que são feitos para conseguirmos reproduzir o mesmo problema.
      placeholder: "Por exemplo: \n1. Entre na pagina site.com.br;\n2. Vá com o mouse até o canto superior direito e localize o botão Nova Conta;\n3. Clique com o botão direito do mouse."
    validations:
      required: true

  - type: textarea
    id: adicional
    attributes:
      label: Ambiente e informações adicionais
      description: Qual dispositivo você usou?
      placeholder: "Por exemplo: \nNavegador: Firefox/100.2.0 e Chrome/43.0.2357.65.\nOS: Ubuntu 20.04."
    validations:
      required: false
